# Site settings
title: Iran University of Science and Technology
course_name: Signals and Systems	
course_description: A signal is a description of how one parameter varies with another parameter
For instance, voltage changing over time in an electronic circuit, or brightness varying with distance in an image
A system is any process that produces an output signal in response to an input signal
This is illustrated by the block diagram in Fig 5-1
Continuous systems input and output continuous signals, such as in analog electronics
Discrete systems input and output discrete signals, such as computer programs that manipulate the values stored in arrays

course_semester: "Fall 2019"
description: |
    Instructor: Dr.Ahmad Akbari	

message: #Please register to our Google <a href="https://groups.google.com/forum/#!forum/gp-id">groups page</a> to get course notifications via email.
baseurl: "/course_template" # the subpath of your site, e.g. /blog/
url: "http://sauleh.github.io/course_template" # the base hostname & protocol for your site
syllabus: http://sauleh.github.io/course_template/syllabus/
githubdir: 

# Author/user information
email: akbari-at-iust.ac.ir
authorurl: "http://borken-url.github.io"
address: |
    School of Computer Engineering
    Iran University of Science and Technology
    Tehran, Iran


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false

sass:
    style: :compressed        

defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
      comments: false



plugins:
    - jekyll-jalali
