# Site settings
title: Iran University of Science and Technology
course_name: Signals and Systems	
course_description: In signal processing, a signal is a function that conveys information about a phenomenon.[1] In electronics and telecommunications, it refers to any time varying voltage, current or electromagnetic wave that carries information. A signal may also be defined as an observable change in a quantity.[2]

Any physical quantity that exhibits variation in space or time can be a signal used, among other possibilities, to share messages between observers.[3] According to the IEEE Transactions on Signal Processing, a signal can be audio, video, speech, image, sonar and radar-related and so on.[4] In a later effort of redefining a signal,[2] anything that is only a function of space, such as an image, is excluded from the category of signals. Also, it is stated that a signal may or may not contain any information.
course_semester: "Fall 2019"
description: |
    Instructor: Dr.Ahmad Akbari

message: #Please register to our Google <a href="https://groups.google.com/forum/#!forum/gp-id">groups page</a> to get course notifications via email.
baseurl: "/course_template" # the subpath of your site, e.g. /blog/
url: "http://sauleh.github.io/course_template" # the base hostname & protocol for your site
syllabus: http://sauleh.github.io/course_template/syllabus/
githubdir: 

# Author/user information
email: instructor-first-name@iust.ac.ir
twitter_username: broken_twitter 
github_username:  broken_github
authorurl: "http://borken-url.github.io"
address: |
    School of Computer Engineering
    Iran University of Science and Technology
    Tehran, Iran


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false

sass:
    style: :compressed        

defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
      comments: false



plugins:
    - jekyll-jalali
 